TAKOYAKI-cake/cake

app/models/genre.rb
app/models/product.rb
db/migrate/20200208052146_create_genres.rb
db/migrate/20200208052153_create_products.rb
test/fixtures/genres.yml
test/fixtures/products.yml
test/models/genre_test.rb
test/models/product_test.rb

Nishimurasyota

---

app/assets/javascripts/admin/genres.coffee
app/assets/javascripts/admin/products.coffee
app/assets/stylesheets/admin/genres.scss
app/assets/stylesheets/admin/products.scss
app/controllers/admin/genres_controller.rb
app/controllers/admin/products_controller.rb
app/helpers/admin/genres_helper.rb
app/helpers/admin/products_helper.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb
config/routes.rb
db/schema.rb
test/controllers/admin/genres_controller_test.rb
test/controllers/admin/products_controller_test.rb

＋スキームの修正をしています。
※db::migrateを行い、スキームに加筆

Add [controllerとview(管理者側の商品とジャンル)]

---

app/models/admin.rb
config/routes.rb
db/schema.rb

Add [orderモデル、admin用テーブル作成]

---

.gitignore

gitignore追加

---

app/models/order.rb
app/models/orderd_product.rb
db/schema.rb

fix [model,schemaの修正]

---

app/models/product.rb

fix [productmodel]

---

app/assets/javascripts/admin/customers.coffee
app/assets/stylesheets/admin/customers.scss
app/controllers/admin/customers_controller.rb
app/helpers/admin/customers_helper.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/index.html.erb
app/views/admin/customers/show.html.erb
app/views/admin/orders/show.html.erb
test/controllers/admin/customers_controller_test.rb

add [customerの一覧、編集]

---

app/controllers/products_controller.rb
app/views/products/index.html.erb
config/initializers/kaminari_config.rb

kaminari設定、商品一覧（とちゅう）

---

app/controllers/admin/products_controller.rb
app/models/product.rb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb
db/migrate/20200210064822_add_genre_id_to_products.rb

商品画面の設定
新規投稿・詳細画面
商品モデルにジャンルのカラムを追加

fix [商品画面の修正、商品にジャンルIDのカラムを付与]

---

app/controllers/admin/products_controller.rb
app/views/admin/products/new.html.erb

商品の画像投稿フォーム
変更後の修正を可能にする
商品一覧から新規作成ページへのリンク作成

fix [admin/product/controller]

---

app/controllers/admin/customers_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/application_controller.rb
app/views/admin/customers/index.html.erb
app/views/admin/orders/index.html.erb
app/views/layouts/application.html.erb

add [adminヘッダー]

---

app/controllers/application_controller.rb
app/controllers/orders_controller.rb
config/routes.rb

add [ヘッダー修正]

---

app/controllers/addresses_controller.rb
app/controllers/orders_controller.rb
app/models/address.rb
app/models/order.rb
app/views/orders/new.html.erb

add [購入情報入力]

---

app/controllers/orders_controller.rb
app/models/product.rb
app/views/orders/confirm_new.html.erb
app/views/orders/new.html.erb
config/routes.rb
db/migrate/20200212080759_add_order_id_to_orderd_products.rb
db/migrate/20200212080911_add_product_id_to_orderd_products.rb
db/schema.rb

add [注文情報画面]

---

app/views/layouts/application.html.erb

Fix[ヘッダー調整]

---

app/controllers/admin/orders_controller.rb
app/controllers/orders_controller.rb
app/models/address.rb
app/views/admin/orders/top.html.erb
app/views/layouts/application.html.erb
app/views/orders/confirm_new.html.erb
app/views/orders/new.html.erb

add [注文情報]

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/all.html.erb
app/views/admin/orders/top.html.erb
app/views/layouts/application.html.erb
config/routes.rb

add [admin　注文一覧]

---

app/assets/javascripts/admin/orderd_products.coffee
app/assets/stylesheets/admin/orderd_products.scss
app/controllers/admin/orderd_products_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/orders_controller.rb
app/helpers/admin/orderd_products_helper.rb
app/views/admin/orderd_products/update.html.erb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/orders/index.html.erb
config/routes.rb
test/controllers/admin/orderd_products_controller_test.rb

会員側の注文履歴一覧表示の個数の表示
管理者側の製作ステータス変更用のコントローラー作成

fix[product/view]

---

app/views/admin/orders/show.html.erb

fix [link設定]

---

app/models/address.rb
app/views/admin/orders/all.html.erb
app/views/admin/orders/show.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/show.html.erb
app/views/carts/index.html.erb
app/views/customers/show.html.erb
app/views/customers/top.html.erb
app/views/orders/confirm_new.html.erb
app/views/orders/new.html.erb
app/views/orders/show.html.erb
app/views/products/genre.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

add [価格、番号表示]

---

app/controllers/admin/orderd_products_controller.rb
app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb
app/views/orders/show.html.erb

fix[管理画面の注文詳細]

---

app/controllers/carts_controller.rb
app/models/product.rb
app/views/admin/products/index.html.erb

add [カート重複]

---

app/controllers/admin/orderd_products_controller.rb
app/controllers/admin/orders_controller.rb
app/views/orders/index.html.erb
app/views/orders/show.html.erb

・ECサイト
→注文履歴詳細画面の金額表記
・管理画面
→注文履歴一覧の表記順の修正

fix[注文履歴画面]
